import Head from 'next/head'
import Link from 'next/link'
import { format, parseISO, add } from 'date-fns'

import { blogPosts } from '../lib/data'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="space-y-4">
        {blogPosts.map((item) => (
          <BlogListItem key={item.slug} {...item} />
        ))}
      </div>
    </div>
  )
}

function BlogListItem({ slug, title, date, content }) {
  return (
    <div className="border border-gray-100 shadow hover:shadow-md rounded p-4">
      <h1><Link href={`/blog/${slug}`}><a className="font-bold text-lg">{title}</a></Link></h1>
      <p className="text-gray-600 text-sm">{format(parseISO(date), 'MMMM do, uuu')}</p>
      <p>{content}</p>
    </div>
  )
}