import Head from 'next/head'
import Link from 'next/link'

import { blogPosts } from '../lib/data'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>My Blog</h1>
      </main>

      <div>
        {blogPosts.map((item) => (
          <div key={item.slug}>
            <h1><Link href={`/blog/${item.slug}`}><a>{item.title}</a></Link></h1>
            <p>{item.data.toString()}</p>
            <p>{item.content}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
